#' Plot Rasters from a VILMA PD Object
#' @description
#' Provides a quick visualization of raster layers from \code{vilma.pd} objects.  
#' For each raster stored in the object, this function displays the grid values 
#' on a map, with numerical values shown per cell.
#'
#' @param x An object of class \code{vilma.pd}, typically the output of a PD calculation.
#' @param ... Additional arguments passed to plotting functions (currently unused).
#'
#' @details
#' This function is designed for quick inspection of phylogenetic diversity or abundance 
#' rasters generated by VILMA. Each raster layer is plotted sequentially, and cell values 
#' are displayed directly on the map. Users can directly access raster data for more 
#' advanced plotting if needed.
#'
#' @return Produces raster plots of the layers contained in the \code{vilma.pd} object. 
#' Invisibly returns the input object.
#'
#' @author 
#' Omar Daniel Leon-Alvarado \url{https://leon-alvarado.weebly.com/}
#' J. Angel Soto-Centeno \url{https://www.mormoops.com}
#'
#' @export
#' @method plot vilma.pd

plot.vilma.pd <- function(x, ...) {
  if (!inherits(x, "vilma.pd")) {
    stop("Input must be an object of class 'vilma.pd'.")
  }
  if (is.null(x$rasters) || length(x$rasters) == 0L) {
    stop("No raster data available for plotting.")
  }

  # Exact titles you use
  title_map <- c(
    "ab.raster" = "Richness raster",
    "r.raster"  = "Abundance Raster",
    "pd.raster" = "PD raster"
  )

  order_vec <- c("ab.raster", "r.raster", "pd.raster")

  # Helper: label finite cell values at cell centers
  .label_cells <- function(r) {
    vals <- try(terra::values(r, mat = FALSE), silent = TRUE)
    if (inherits(vals, "try-error") || length(vals) == 0) return(invisible())
    idx <- which(is.finite(vals))
    if (!length(idx)) return(invisible())
    xy <- try(terra::xyFromCell(r, idx), silent = TRUE)
    if (inherits(xy, "try-error")) return(invisible())
    graphics::text(xy[,1], xy[,2], labels = round(vals[idx]),
                   cex = 0.7, col = "white")
    invisible()
  }

  # Plot each available raster in the strict order
  for (nm in order_vec) {
    if (!nm %in% names(x$rasters)) next
    r <- x$rasters[[nm]]
    if (terra::nlyr(r) > 1) r <- r[[1]]

    terra::plot(r, main = title_map[[nm]], ...)
    .label_cells(r)
    Sys.sleep(1)  # 1-second pause between plots
  }

  invisible(x)
}


