#' Plot VILMA Regionalization Rasters
#'
#' Provides a quick visualization of a \code{vilma.region} object produced by
#' \code{\link{vilma.regionalize}}. The plot shows two maps in a vertical layout:
#' (i) the raster of region (group) IDs and (ii) the raster of mean within-region
#' phylogenetic dissimilarity (mean PD distance) per cell.
#'
#' @param x An object of class \code{vilma.region}, typically generated by
#'   \code{\link{vilma.regionalize}}.
#' @param ... Additional arguments (currently not used).
#'
#' @details
#' This method is intended for quick inspection of regionalization results.
#' Internally it uses \code{\link[terra]{plot}} to display the rasters stored in
#' \code{x$raster}. A small helper is included to optionally label cells with
#' numeric values when the raster contains finite values.
#'
#' @return Produces raster plots for the region IDs and mean within-region
#' dissimilarity. Invisibly returns \code{x}.
#'
#' @author
#' Omar Daniel Leon-Alvarado \url{https://leon-alvarado.weebly.com/}
#' J. Angel Soto-Centeno \url{https://www.mormoops.com/}
#'
#' @seealso \code{\link{vilma.regionalize}}, \code{\link[terra]{plot}}
#'
#' @export
#' @method plot vilma.region

plot.vilma.region <- function(x, ...){

  if(!inherits(x, "vilma.region")){
    stop("Input must be an object of class 'vilma.region'")
  }
  
  # small helper to safely annotate numbers on a SpatRaster
  .label_cells <- function(r){
    vals  <- try(terra::values(r), silent = TRUE)
    if (inherits(vals, "try-error") || length(vals) == 0) return(invisible())
    # finite indices
    idx   <- which(is.finite(vals))
    if (length(idx) == 0) return(invisible())
    crds  <- try(terra::xyFromCell(r, idx), silent = TRUE)
    if (inherits(crds, "try-error")) return(invisible())
    graphics::text(crds[,1], crds[,2], labels = round(vals[idx], 2),
                   cex = 0.6, col = "white")
    invisible()
  }
  
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  
  par(mfrow = c(2,1), mar = c(3,3,3,5))
  
  terra::plot(x$raster$group.raster, main = "beta-PD Groups")
  terra::plot(x$raster$mean.group.raster, main = "Mean beta-PD by Group")
  
  invisible(x)
 
}
