#' Plot Rasters from a VILMA PD Object
#' @description
#' Provides a quick visualization of raster layers from \code{vilma.pd} objects.  
#' For each raster stored in the object, this function displays the grid values 
#' on a map, with numerical values shown per cell.
#'
#' @param x An object of class \code{vilma.pd}, typically the output of a PD calculation.
#' @param ... Additional arguments passed to plotting functions (currently unused).
#'
#' @details
#' This function is designed for quick inspection of phylogenetic diversity or abundance 
#' rasters generated by VILMA. Each raster layer is plotted sequentially, and cell values 
#' are displayed directly on the map. Users can directly access raster data for more 
#' advanced plotting if needed.
#'
#' @return Produces raster plots of the layers contained in the \code{vilma.pd} object. 
#' Invisibly returns the input object.
#'
#' @author 
#' Omar Daniel Leon-Alvarado \url{https://leon-alvarado.weebly.com/}
#' J. Angel Soto-Centeno \url{https://www.mormoops.com}
#'
#' @export
#' @method plot vilma.pd

plot.vilma.pd <- function(x, ...){
  
  if (!inherits(x, "vilma.pd")) {
    stop("Input must be an object of class 'vilma.pd'.")
  }
  if (is.null(x$rasters) || length(x$rasters) == 0L) {
    stop("No raster data available for plotting.")
  }
  if (is.null(x$rasters$pd.raster)) {
    # Keep your original guard text, but allow plotting other rasters too:
    # Fall back to plotting whatever exists, instead of stopping hard.
    # If you prefer strict behavior, restore the stop() here.
    # stop("No raster data available for plotting.")
    message("Note: 'pd.raster' not found; plotting available rasters in 'x$rasters'.")
  }
  
  .label_cells <- function(r){
    vals <- try(terra::values(r), silent = TRUE)
    if (inherits(vals, "try-error") || length(vals) == 0) return(invisible())
    mask <- is.finite(vals)
    if (!any(mask)) return(invisible())
    idx  <- which(mask)
    crds <- try(terra::xyFromCell(r, idx), silent = TRUE)
    if (inherits(crds, "try-error")) return(invisible())
    graphics::text(crds[,1], crds[,2], labels = round(vals[idx], 2),
                   cex = 0.6, col = "white")
    invisible()
  }
  
  rnames <- names(x$rasters)
  for (i in seq_along(x$rasters)) {
    nm <- if (!is.null(rnames) && nzchar(rnames[i])) {
      if (identical(rnames[i], "ab.raster")) "Abundance Raster" else paste(rnames[i], "Raster")
    } else {
      if (i == 1) "Abundance Raster" else paste("Raster", i)
    }
    terra::plot(x$rasters[[i]], main = nm)
    .label_cells(x$rasters[[i]])
    Sys.sleep(1)
  }
  
  invisible(x)  
}

