#' Plot VILMA Distribution Rasters
#' @description
#' Provides a quick visualization of a \code{vilma.dist} object, including:
#' \itemize{
#'   \item \strong{Species Richness Raster} – Displays species richness per cell with numerical values.
#'   \item \strong{Abundance Raster} – Displays species abundance per cell with numerical values.
#' }
#'
#' @param x An object of class \code{vilma.dist}, typically generated by \code{points.to.raster()}.
#' @param ... Additional arguments passed to plotting functions (currently not used).
#'
#' @details
#' This function is intended for quick inspection of VILMA distribution objects.
#' It plots both species richness and abundance rasters, labeling each cell with its value.
#' 
#' @return Produces raster plots for richness and abundance. No values are returned.
#'
#' @author 
#' Omar Daniel Leon-Alvarado \url{https://leon-alvarado.weebly.com/}
#' J. Angel Soto-Centeno \url{https://www.mormoops.com}
#' 
#' @export
#' @method plot vilma.dist

plot.vilma.dist <- function(x, ...){
  
  if (!inherits(x, "vilma.dist")) {
    stop("Input must be an object of class 'vilma.dist'.")
  }
  if (is.null(x$r.raster) || is.null(x$ab.raster)) {
    stop("This 'vilma.dist' object was created with 'doRast = FALSE' or lacks rasters.")
  }
  
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par))
  
  par(mfrow = c(2, 1), mar = c(3, 3, 3, 5))
  
  .label_cells <- function(r){
    vals <- try(terra::values(r), silent = TRUE)
    if (inherits(vals, "try-error") || length(vals) == 0) return(invisible())
    mask <- is.finite(vals)
    if (!any(mask)) return(invisible())
    idx  <- which(mask)
    crds <- try(terra::xyFromCell(r, idx), silent = TRUE)
    if (inherits(crds, "try-error")) return(invisible())
    graphics::text(crds[,1], crds[,2], labels = round(vals[idx], 2),
                   cex = 0.6, col = "white")
    invisible()
  }
  
  # Richness
  terra::plot(x$r.raster, main = "Species Richness Raster")
  #.label_cells(x$r.raster)
  
  # Abundance
  terra::plot(x$ab.raster, main = "Abundance Raster")
  #.label_cells(x$ab.raster)
  
  invisible(x)
}

