#' Print Summary of a VILMA Null Model
#' @description
#' Displays a textual summary of a \code{vilma.null} object. Depending on the null model method,
#' it prints either global PD statistics or cell-specific SES and p-values.
#'
#' @param x An object of class \code{vilma.null}, typically generated by a VILMA null model function.
#' @param ... Additional arguments (currently unused).
#'
#' @details
#' For objects with \code{Method = "global"}, the function reports observed PD, mean and SD of null PD,
#' standardized effect size (SES), and whether the p-value is \code{< 0.05}. For \code{Method = "cell"}, it
#' prints summary statistics of PD, null PD, SES per cell, and the number of cells with significant p-values.
#'
#' @return Invisibly returns the input object. Primary purpose is printing a summary to the console.
#'
#' @author Omar Daniel Leon-Alvarado \url{https://leon-alvarado.weebly.com/}
#' J. Angel Soto-Centeno \url{https://www.mormoops.com}
#'
#' @export
#' @method print vilma.null

print.vilma.null <- function(x, ...){
  # 1. Input validation
  if (!inherits(x, "vilma.null")) {
    stop("Object must be of class 'vilma.null'")
  }
  
  if (x$Method == "global") {
    cat("\n")
    cat("vilam.null Object Summary")
    cat("\n")
    cat(paste("Method :", x$Method))
    cat("\n")
    cat(paste("Iterations :", x$Iterations))
    cat("\n")
    cat("-------------------------")
    cat("\n\n")
    
    cat(sprintf("  - Observed PD: %.1f \n", x$pd.obs))
    cat(sprintf("  - Null PD (mean): %.1f \n", mean(x$null.pd, na.rm = TRUE)))
    cat(sprintf("  - Null PD (sd): %.1f \n", sd(x$null.pd, na.rm = TRUE)))
    cat(sprintf("  - Standardized Effect Size (SES): %.1f \n", x$SES))
    
    if (x$Pvalue < 0.05) {
      cat("  - P-value < 0.05 \n\n")
    } else {
      cat("  - P-value > 0.05 \n\n")
    }
  }
  
  if (x$Method == "cell") {
    cat("\n")
    cat("vilam.null Object Summary")
    cat("\n")
    cat(paste("Method :", x$Method))
    cat("\n")
    cat(paste("Iterations :", x$Iterations))
    cat("\n")
    cat("-------------------------")
    cat("\n\n")
    
    cat(sprintf("  - Observed PD (range): %.1f - %.1f [Mean = %.1f +/- %.1f] \n",
      min(x$CellValues$PD), max(x$CellValues$PD, na.rm = TRUE),
      mean(x$CellValues$PD, na.rm = TRUE), sd(x$CellValues$PD, na.rm = TRUE)
    ))
    
    cat(sprintf("  - Null PD (range): %.1f - %.1f [Mean = %.1f +/- %.1f] \n",
      min(x$CellValues$NullPD, na.rm = TRUE), max(x$CellValues$NullPD, na.rm = TRUE),
      mean(x$CellValues$NullPD, na.rm = TRUE), sd(x$CellValues$NullPD, na.rm = TRUE)
    ))
    
    cat(sprintf("  - Standardize Effect Size (range): %.1f - %.1f [Mean = %.1f +/- %.1f] \n",
      min(x$CellValues$SES, na.rm = TRUE), max(x$CellValues$Pvalue, na.rm = TRUE),
      mean(x$CellValues$Pvalue, na.rm = TRUE), sd(x$CellValues$Pvalue, na.rm = TRUE)
    ))
    
    cat(sprintf("  - P-value: %d Cells out of %d with p-value < 0.05 \n",
      sum(x$CellValues$Pvalue < 0.05), length(x$CellValues$Pvalue)
    ))
  }
  
  cat("\n\n")
}

